import Head from "next/head";
import Link from "next/link";
import styles from "@styles/Home.module.css";
import { useState, useEffect, useContext } from "react";
import { AppContext } from "@context/AppContext";
import Button from "@mui/material/Button";
import Typography from "@mui/material/Typography";
import imgs from "@assets/img/imgs.js";


export default function Context1() {
  const [visible, setIsVisible] = useState(false);
  const [open, setOpen] = useState(false);

  const { secVideo } = useContext(AppContext);
  const [sharedState] = secVideo;

  useEffect(() => {
    let vid = document.getElementById("myVideo");
    vid.currentTime = sharedState;

    vid.addEventListener("timeupdate", function () {
      //currentTime use second, if you want min *60
      if (vid.currentTime >= 35) {
        setIsVisible(true);
      }
      if (vid.currentTime >= 45) {
        vid.pause();
      }
    });
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Contexto 1</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <video
          id="myVideo"
          src="https://res.cloudinary.com/gregoryinnovo/video/upload/v1652886794/1_zd5zh4.mp4"
          width="100%"
          height="780"
          controls
          autoPlay
        >
          <source src="movie.mp4" type="video/mp4" />
        </video>
        {visible && (
          <div className="containerOptions">
            <Typography
              sx={{
                mt: 2,
                backgroundColor: "primary.dark",
                color: "white",
                fontWeight: "bold",
                fontSize: 18,
                textAlign: "center",
                p: 1,
              }}
            >
              ¿Qué decidió estudiar Sergio fajardo?
            </Typography>
            <Button  className='styles_button_option' variant="contained" sx={{ mt: 1, mb: 1 }}>
              
              <figcaption>Matemáticas</figcaption>
              <Link sx={{ mt: 2 }} href="/context1/opcion1">
                <img
                  src={imgs[0]}
                  alt="imagen de la opcion 1"
                  width="150"
                  height="150"
                />
              </Link>
            </Button>
            <Button className='styles_button_option' variant="contained" sx={{ mt: 1, mb: 1 }}>
              
              <figcaption>Astronomía</figcaption>
              <Link sx={{ mt: 2 }} href="/context1/opcion2">
              <img
                src={imgs[1]}
                alt="imagen de la opcion 2"
                width="150"
                height="150"
              />
              </Link>
            </Button>
          </div>
        )}
      </main>
    </div>
  );
}
