import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import styles from "@styles/Home.module.css";
import { useState, useEffect, useContext } from "react";

import { AppContext } from "@context/AppContext";
/*
  Página donde se muestra el contexto 2 con video con las 2 
  opciones
*/
import imgs from "@assets/img/imgs.js";
import Button from "@mui/material/Button";
import Typography from "@mui/material/Typography";


export default function Context3() {
  const [open, setOpen] = useState(false);
  const { secVideo } = useContext(AppContext);
  const [sharedState] = secVideo;
  const [visible, setIsVisible] = useState(false);

  useEffect(() => {
    let vid = document.getElementById("myVideo");
    vid.currentTime = sharedState;
    vid.webkitRequestFullScreen();

    vid.addEventListener("timeupdate", function () {
      //currentTime use second, if you want min *60
      if (vid.currentTime >= 32) {
        setIsVisible(true);
      }
    });
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Contexto 3</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <video
          id="myVideo"
          src="https://res.cloudinary.com/gregoryinnovo/video/upload/v1652886829/3_jms6u0.mp4"
          width="100%"
          height="780"
          controls
          autoPlay
        >
          <source src="movie.mp4" type="video/mp4" />
        </video>
        {visible && (
          <div className="containerOptions">
            <Typography
              sx={{
                mt: 2,
                backgroundColor: "primary.dark",
                color: "white",
                fontWeight: "bold",
                fontSize: 18,
                textAlign: "center",
                p: 1,
              }}
            >
              ¿Qué hizo durante su alcaldía?
            </Typography>
            <Button variant="contained" sx={{ mt: 1, mb: 1 }}>
              {/* <img
                src={imgs[2]}
                alt="imagen de la opcion 1"
                width="150"
                height="150"
              /> */}
              <Link sx={{ mt: 2 }} href="/context3/opcion2">
                Se construyó e inauguró, con presencia de los entonces reyes de
                España Juan Carlos I y Sofía de Grecia, la Biblioteca España,
                financiada con recursos internacionales Corona Española, la cual
                tuvo que ser cerrada por problemas estructurales, hasta la fecha
                enero de 2021.
              </Link>
            </Button>
            <Button variant="contained" sx={{ mt: 1, mb: 1 }}>
              {/* <img
                src={imgs[3]}
                alt="imagen de la opcion 2"
                width="250"
                height="150"
              /> */}
              <Link sx={{ mt: 2 }} href="/context3/opcion1">
                Cuando fui gobernador de Antioquia se comenzó la construcción de
                hidroituango que va a suplir el 17% de la demanda energética del
                país.
              </Link>
            </Button>
          </div>
        )}
      </main>
    </div>
  );
}
