import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '@styles/Home.module.css'
import YouTube from "react-youtube";
import {useState, useEffect, useContext } from 'react';

import {AppContext} from '@context/AppContext';
/*
  Página donde se muestra el contexto 2 con video con las 2 
  opciones
*/
import Backdrop from '@mui/material/Backdrop';
import Box from '@mui/material/Box';
import Modal from '@mui/material/Modal';
import Fade from '@mui/material/Fade';
import Button from '@mui/material/Button';
import Typography from '@mui/material/Typography';


const style = {
  position: 'absolute',
  top: '50%',
  left: '50%',
  transform: 'translate(-50%, -50%)',
  width: 400,
  bgcolor: 'background.paper',
  border: '2px solid #000',
  boxShadow: 24,
  p: 4,
  justifyContent:"space-around",
  alignItems:"center",
  direction:'column'
};

export default function Context3() {

 const [isEnd, setIsEnd] = useState(false);
 const [seconds, setSeconds] = useState(0);
 const [open, setOpen] = useState(false);
 const handleOpen = () => setOpen(true);
 const handleClose = () => setOpen(false);

 const { secVideo } = useContext(AppContext);
 const [ sharedState ] = secVideo;

  return (
    <div className={styles.container}>
      <Head>
        <title>Contexto 3</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <YouTube 
          videoId="hrsL-El8Lus" 
          opts={{
            height: "780",
            width: "100%",
            playerVars: {
              autoplay: 1,
              start: sharedState,
          }}}
          onEnd={() => {
            setIsEnd(true)
            handleOpen()
          }}
        />
       
      <Modal
        aria-labelledby="transition-modal-title"
        aria-describedby="transition-modal-description"
        open={open}
        onClose={handleClose}
        closeAfterTransition
        BackdropComponent={Backdrop}
        BackdropProps={{
          timeout: 500,
        }}
      >
        <Fade in={open}>
          <Box sx={style}>
            <Typography id="transition-modal-title" variant="h6" component="h2">
              Pregunta 3
            </Typography>
            <Typography id="transition-modal-description" sx={{ mt: 2 }}>
              ¿Qué hizo durante su alcaldía?
            </Typography>
            <Button>
            <Link sx={{mt:2}} href="/context3/opcion2"> Se construyó e inauguró, con presencia de los entonces reyes de España Juan Carlos I y Sofía de Grecia, la Biblioteca España, financiada con recursos internacionales Corona Española, la cual tuvo que ser cerrada por problemas estructurales, hasta la fecha enero de 2021.</Link>
            </Button>
            <Button>
            <Link sx={{mt:2}} href="/context3/opcion1">Cuando fui gobernador de Antioquia se comenzó la construcción de hidroituango que va a suplir el 17% de la demanda energética del país.</Link>
            </Button>
          </Box>
        </Fade>
      </Modal>
        {
          isEnd &&
          (
            <div className={styles.containerOptions}>
              <h3 className={styles.titleOptions}>
                ¿Qué deberias hacer?
              </h3>
              <Button onClick={handleOpen}>Abrir preguntas</Button>
            </div>
          )
        }
      </main>
    </div>
  )
}

