import * as React from 'react';
import Head from 'next/head'
import styles from '@styles/Main.module.css'
import {useState, useEffect, useContext } from 'react';
import {AppContext} from '@context/AppContext';
import TextField from '@mui/material/TextField';
import Button from '@mui/material/Button';
import Stack from '@mui/material/Stack';
import Typography from '@mui/material/Typography';
import Link from 'next/link';

/* 
  Pantalla principal donde podemos ir a ver la información del candidato o
  iniciar la E.M. al ingresar el nombre
  
  YouTube API:
  https://www.npmjs.com/package/react-youtube

*/
export default function Home() {

 const { userName } = useContext(AppContext);
 const [ name, setName ] = userName;

  const handleChange = (event) => {
    console.log("Se cambia el nombre")
    setName(event.target.value);
    console.log(name)
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Stack 
        direction={{ xs: 'column', sm: 'column' }}
       justifyContent="center"
      alignItems="center"
          sx={{m: 0, maxWidth: '100%', flexWrap: "wrap"}}
          >
        <Typography variant="h3" component="h3" sx={{fontWeight:'bold', mb: 1, mt:10}}>
         El diario de Fercho
        </Typography>
        <Typography variant="h6" component="h6" sx={{fontWeight:'semibold', mb: 8, mt:8, ml:10, mr:10}}alignItems="center" justifyContent="center">
         Bienvenido estudiante de la Universidad Autónoma de Occidente, VIR POLITICA SMA, le permitira obtener información de forma dinámica del candidato presidencial Sergio Fajardo.
        </Typography>
        <Typography variant="h6" component="h6" sx={{fontWeight:'semibold', mb: 8, mt:8, ml:10, mr:10}}>
         Si desea, ingrese el nombre para iniciar.
        </Typography>
        <TextField
          id="outlined-name"
          label="Nombre"
          placeholder="¿Cuál es tu nombre?"
          value={name}
          onChange={handleChange}
          sx={{backgroundColor:"red"}}
        />
        <Link variant="contained" sx={{mt:2, mb:2}} href="/context1/context1" onClick={() => setName(name)} >Iniciar experiencia</Link>
        <Button  variant="contained" sx={{mt:0, mb:2, backgroundColor: "#c4c4c4"}} href="/info" >Revisa la información del candidato</Button>
    </Stack>
    </div>
  )
}


