import * as React from 'react';
import Head from 'next/head';
import styles from '@styles/Main.module.css';
import {useContext } from 'react';
import {AppContext} from '@context/AppContext';
import TextField from '@mui/material/TextField';
import Button from '@mui/material/Button';
import Stack from '@mui/material/Stack';
import Typography from '@mui/material/Typography';
import Link from 'next/link';

import Card from '@mui/material/Card';
import CardActions from '@mui/material/CardActions';
import CardContent from '@mui/material/CardContent';
import CardMedia from '@mui/material/CardMedia';


/* 
  Pantalla principal donde podemos ir a ver la información del candidato o
  iniciar la E.M. al ingresar el nombre
  
  YouTube API:
  https://www.npmjs.com/package/react-youtube

*/
export default function Home() {

 const { userName } = useContext(AppContext);
 const [ name, setName ] = userName;

  const handleChange = (event) => {
    console.log("Se cambia el nombre")
    setName(event.target.value);
    console.log(name)
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>El diario de Fercho</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Stack 
        direction={{ xs: 'column', sm: 'column' }}
       justifyContent="center"
      alignItems="center"
          sx={{m: 10, maxWidth: '100%', flexWrap: "wrap"}}
          >
      <Card sx={{ maxWidth: 645 }}>
      <CardContent>
        <Typography gutterBottom variant="h5" component="div">
          El diario de Fercho
        </Typography>
        <Typography variant="body2" color="text.secondary">
          Bienvenido estudiante de la Universidad Autónoma de Occidente, VIR POLITICA SMA, le permitirá obtener información de forma dinámica del candidato presidencial Sergio Fajardo.
        </Typography>
        <Typography variant="body2" color="text.secondary">
          Si desea, ingrese el nombre para iniciar.
        </Typography>
        <TextField
          id="outlined-name"
          label="Nombre"
          placeholder="¿Cuál es tu nombre?"
          value={name}
          onChange={handleChange}
          sx={{mb: 3, mt:3}}
        />
      </CardContent>
      <CardActions>
        <Button>
          <Link variant="contained" href="/context1/context1" onClick={() => setName(name)} >Iniciar experiencia</Link>
        
        </Button>
        <Button>
        <Link variant="contained" href="/info" onClick={() => setName(name)} >Revisa la información del candidato</Link>
        </Button>
      </CardActions>
    </Card>
    </Stack>
    </div>
  )
}


