import * as React from 'react';
import Head from 'next/head';
import styles from '@styles/Main.module.css';
import {useContext } from 'react';
import {AppContext} from '@context/AppContext';
import TextField from '@mui/material/TextField';
import Button from '@mui/material/Button';
import Stack from '@mui/material/Stack';
import Typography from '@mui/material/Typography';
import Link from 'next/link';

import Card from '@mui/material/Card';
import CardActions from '@mui/material/CardActions';
import CardContent from '@mui/material/CardContent';
import CardMedia from '@mui/material/CardMedia';
import imgs from "@assets/img/imgs.js";
import { blueGrey } from '@mui/material/colors';

/* 
  Pantalla principal donde podemos ir a ver la información del candidato o
  iniciar la E.M. al ingresar el nombre
  
  YouTube API:
  https://www.npmjs.com/package/react-youtube

*/
export default function Home() {

 const { userName } = useContext(AppContext);
 const [ name, setName ] = userName;

  const handleChange = (event) => {
    console.log("Se cambia el nombre")
    setName(event.target.value);
    console.log(name)
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>El diario de Fercho</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Stack 
        direction={{ xs: 'column', sm: 'column' }}
       justifyContent="center"
      alignItems="center"
          sx={{m: 10, maxWidth: '100%', flexWrap: "wrap"}}
          >
      <Card className='styles_card' sx={{ maxWidth: 645 }}>
      <CardContent className='styles_cardContent'>
        {/* <Typography gutterBottom variant="h5" component="div">
          El diario de Fercho
        </Typography> */}
        <img
                src={imgs[4]}
                alt="El diario de Fercho"
                width="450"
                height="250"
        />
        <Typography className='styles_Typography'>
          Bienvenido estudiante de la Universidad Autónoma de Occidente, Media Collab, le permitirá obtener información de forma dinámica del candidato presidencial Sergio Fajardo.
        </Typography>
        <Typography className='styles_Typography'>
          Si desea, ingrese el nombre para iniciar.
        </Typography>
        <TextField 
          id="outlined-name"
          label="Nombre completo"
          placeholder="¿Cuál es tu nombre?"
          value={name}
          onChange={handleChange}
          sx={{mb: 3, mt:3}}
        />
      </CardContent>
      <CardActions className='styles_cardActions'>
        <Button className='styles_Button'>
          <Link variant="contained" href="/context1/context1" onClick={() => setName(name)} >Iniciar experiencia</Link>
        
        </Button>
        <Button className='styles_Button'>
        <Link variant="contained" href="/info" onClick={() => setName(name)} >Más información</Link>
        </Button>
      </CardActions>
    </Card>
    </Stack>
    </div>
  )
}


