import * as React from 'react';
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '@styles/Main.module.css'
import YouTube from "react-youtube";
import {useState, useEffect, useContext } from 'react';
import {AppContext} from '@context/AppContext';
import Box from '@mui/material/Box';
import TextField from '@mui/material/TextField';
import Button from '@mui/material/Button';
import Stack from '@mui/material/Stack';
import Typography from '@mui/material/Typography';

/*
  Página que muestra la información del candidato, red
  de contactos, biografía
*/
export default function Info() {

 const [isEnd, setIsEnd] = useState(false);
 const [seconds, setSeconds] = useState(0);
 const {sharedState} = useContext(AppContext);

const [name, setName] = React.useState('');
  const handleChange = (event) => {
    setName(event.target.value);
  };

  
  return (
    <div className={styles.container}>
      <Head>
        <title>Información del candidato</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Stack 
        direction={{ xs: 'column', sm: 'column' }}
       justifyContent="center"
      alignItems="center"
          sx={{m: 0, maxWidth: '100%', flexWrap: "wrap"}}
          >
        <Typography variant="h3" component="h3" sx={{fontWeight:'bold', mb: 3, mt:3}}>
         Sergio Fajardo
        </Typography>
        <img src="https://www.semana.com/resizer/DyT-vLgdK8Q85mAyxP68mSo12IQ=/1200x675/filters:format(jpg):quality(50)//cloudfront-us-east-1.images.arcpublishing.com/semana/ROSC5HZRYNBXRGDZPTA726TT24.jpg" width="50%" height="auto" />
        <Typography variant="h6" component="h6" sx={{ ml: 5, mr:5}}>
         Sergio Fajardo, nacido en la ciudad de Medellín Antioquía, es matemático, profesor e investigador, un candidato presidencial del grupo Centro de esperanza, para las elecciones presidenciales del año 2022, en el 2018 se postuló para la presidencia con la Alianza Verde, Polo Democrático y su propio movimiento. También fue gobernador de Antioquia en el 2012 hasta el 2015.

Sergio Fajardo, fue profesor de la Universidad de los Andes enseñando matemáticas, e investigador, también compartió columnas de opinión en varios medios de comunicación, gracias a ello fue reconocido como el miembro de la comisión facilitadora de la paz en antioquia, con apoyo del expresidente Alvaro Uribe Vélez en compañía com Samper, permitiéndole conocer profundamente los problemas del conflicto departamental con políticos, guerrilleros y empresarios.

        </Typography>


        <Typography variant="h6" component="h6" sx={{ ml: 5, mr:5 }}>
        Resaltando un poco su carrera política, en 1999 dio paso como director del centro de ciencias y tecnologías gracias al apoyo del vicepresidente Gustavo Bell y por su gran hoja de vida y recorrido.

“Después de una gobernación muy exitosa, Fajardo salió con altos niveles de popularidad. Pero aún así no pudo dejar a su sucesor Federico Restrepo en su silla. Le ganó ampliamente su rival Luis Pérez, apoyado por Juan Manuel Santos y el vicepresidente Germán Vargas. En la Alcaldía de Medellín tampoco triunfó su ex secretario de Gobierno Alonso Salazar.

        </Typography>


        <Typography variant="h6" component="h6" sx={{ ml: 5, mr:5 }}>
        En 2016, Fajardo hizo campaña a favor del plebiscito, y arrancó con ella su campaña presidencial para el 2018. En junio de 2017, oficializó la coalición de los Ni-ni con la senadora de la Alianza Verde Claudia López y el del Polo Jorge Enrique Robledo.
En diciembre de 2017 y luego de recoger casi un millón de firmas para inscribir su candidatura, hubo una crisis dentro de la coalición porque no había acuerdo para escoger al candidato. Fajardo quería que lo ungieron a él, mientras que Robledo y Claudia querían una consulta en marzo. Al final el exgobernador ganó el pulso y fue anunciado como el candidato presidencial del Polo y los Verdes.
No pudo, sin embargo, aglutinar las bases de izquierda de esos dos partidos, que en su mayoría se fueron con Petro.
En la primera vuelta de las presidenciales de mayo de 2018 quedó tercero con 4,5 millones de votos, por debajo de Iván Duque (7,5 millones) y Gustavo Petro (4,8 millones).
Para la segunda vuelta votó en blanco.

        </Typography>

        <Typography variant="h6" component="h6" sx={{ ml: 5, mr:5}}>
        En junio del 2020 la Fiscalía ordenó compulsar copias de la denuncia por la que se detuvo al gobernador de Antioquia, Aníbal Gaviria, para investigarlo a él también. Eso dado que la ejecución del contrato que enloda a Gaviria también se llevó a cabo durante su administración en la Gobernación de ese departamento. 
Tanto a Gaviria como a Fajardo (al igual que a Luis Alfredo Ramos) los investiga la Fiscalía por presunta corrupción en la construcción de la troncal de La Paz en Caucasia, frente a lo cual Sergio Fajardo reveló la liquidación del contrato se hizo antes de que él se posesionó como Gobernador.
En marzo de 2022 se convirtió, con poco más de 700 mil votos, en el candidato oficial de la Coalición Centro Esperanza.
“Silla vacía - Marzo 22/2022

Información recuperada en: La sillavacia https://www.lasillavacia.com/quien-es-quien/sergio-fajardo 
        </Typography>

        <Typography variant="h6" component="h6" sx={{fontWeight:'bold', mb: 3, mt:3}}>
         Red de contactos
        </Typography>
        <Typography variant="h6" component="h6">
          <ul>
            <li>Alfonso Prada: Ex Secretario General de la Presidencia y jefe de debate de Gustavo Petro.</li>
            <li>Luis Eduardo Garzón:Ex alcalde de Bogotá y ex ministro de Trabajo</li>
            <li>John Sudarsky Rosenbaum: Ex senador de Alianza Verde</li>
            <li>Antanas Mockus: Exalcalde de Bogotá</li>
            <li>Enrique peñalosa Londoño: Exalcalde de Bogotá</li>
            <li>Claudia López: Alcaldesa de Bogotá</li>
          </ul>
        </Typography>
        <YouTube 
          videoId="c9ZgxpkQvpo" 
          opts={{
            height: "420",
            width: "100%",}}
          onEnd={() => {
            setIsEnd(true)
            handleOpen()
          }}
        />
        <Button variant="contained" sx={{m:10}} href="/">Regresar al inicio</Button>
    </Stack>
    </div>
  )
}