import React, { useState, useEffect } from "react";
import Head from "next/head";
import styles from "@styles/Home.module.css";
import Link from "next/link";
import { useContext } from "react";
import { AppContext } from "@context/AppContext";
import YouTube from "react-youtube";
import Button from "@mui/material/Button";
import Snackbar from "@mui/material/Snackbar";
import MuiAlert from "@mui/material/Alert";

const Alert = React.forwardRef(function Alert(props, ref) {
  return <MuiAlert elevation={6} ref={ref} variant="filled" {...props} />;
});

/*
  Opción correcta de todos los contextos
*/

export default function OpcionCorrecta({
  value,
  linkUrl,
  videoId,
  medalMessage,
}) {
  const [isEnd, setIsEnd] = useState(false);
  const [open, setOpen] = useState(false);

  const { secVideo, medallaUno, medallaDos, medallaTres, medallaCuatro } =
    useContext(AppContext);
  const [sharedState, setSharedState] = secVideo;
  const [medalla1, setMedalla1] = medallaUno;
  const [medalla2, setMedalla2] = medallaDos;
  const [medalla3, setMedalla3] = medallaTres;
  const [medalla4, setMedalla4] = medallaCuatro;

  const handleClick = () => {
    setOpen(true);
  };

  useEffect(() => {
    setSharedState(0);
    showMedals();
    let vid = document.getElementById("myVideo");
    vid.currentTime = 0;
    vid.webkitRequestFullScreen();

    vid.addEventListener("timeupdate", function () {
      //currentTime use second, if you want min *60
      if (vid.currentTime >= 5) {
        
        setIsEnd(true);
      }
    });
  }, []);

  const showMedals = () => {
    switch (value) {
      case 1:
        if (medalla1 != 1) {
          handleClick();
          setMedalla1(2);
          console.log("Muestro la medalla obtenida");
        } else {
          console.log("No muestro la medalla", medalla1);
        }
        break;
      case 2:
        if (medalla2 != 1) {
          handleClick();
          setMedalla2(2);
          console.log("Muestro la medalla obtenida");
        } else {
          console.log("No muestro la medalla", medalla2);
        }
        break;
      case 3:
        if (medalla3 != 1) {
          handleClick();
          setMedalla3(2);
          console.log("Muestro la medalla obtenida");
        } else {
          console.log("No muestro la medalla", medalla3);
        }
        break;
      case 4:
        if (medalla4 != 1) {
          handleClick();
          setMedalla4(2);
          console.log("Muestro la medalla obtenida");
        } else {
          console.log("No muestro la medalla", medalla4);
        }
        break;
      default:
        console.log("No envio nada");
        break;
    }
  };

  const handleClose = (event, reason) => {
    if (reason === "clickaway") {
      return;
    }

    setOpen(false);
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>CORRECTA</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Snackbar open={open} autoHideDuration={6000} onClose={handleClose}>
          <Alert
            onClose={handleClose}
            severity="success"
            sx={{ width: "100%" }}
          >
            Medalla conseguida: {medalMessage}
          </Alert>
        </Snackbar>

        <video
          id="myVideo"
          src={videoId}
          width="100%"
          height="780"
          controls
          autoPlay
        >
          <source src="movie.mp4" type="video/mp4" />
        </video>
        {/* <YouTube
          videoId={videoId}
          opts={{
            height: "780",
            width: "100%",
            playerVars: {
              autoplay: 1,
            },
          }}
          onEnd={() => {
            setSharedState(0);
            setIsEnd(true);
          }}
        /> */}
      </main>

      {isEnd && (
        <main>
          <Button>
            <Link href={linkUrl}>Siguiente</Link>
          </Button>
        </main>
      )}
    </div>
  );
}
